apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000

